//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOnIntercompany.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOnIntercompany.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF (:object_type = &apos;17&apos; ) and :transaction_type = &apos;A&apos; and (:error =0) THEN
        ///	CALL &quot;SBO_EXX_INDO_PTN_OBJ017_ORDR&quot; (:list_of_cols_val_tab_del, :transaction_type, :error, :error_message);
        ///END IF;
        ///
        ///IF :object_type = &apos;22&apos; and (:transaction_type = &apos;A&apos; OR :transaction_type = &apos;U&apos;) and (:error =0) THEN
        ///	CALL &quot;SBO_EXX_INDO_PTN_OBJ020_OPOR&quot; (:list_of_cols_val_tab_del, :transaction_type, :error, :error_message);
        ///END IF;.
        /// </summary>
        internal static string PostTransaction {
            get {
                return ResourceManager.GetString("PostTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SBO_EXX_INDO_PTN_OBJ017_ORDR&quot;
        ///(
        ///	IN docEntry integer
        ///	, IN transaction_type nchar(1)
        ///	, OUT error integer
        ///	, OUT error_message nvarchar(200)
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN 
        ///
        ///	IF :transaction_type = &apos;A&apos; OR :transaction_type = &apos;U&apos;  THEN		
        ///		UPDATE ORDR 
        ///		SET &quot;U_EXX_INDO_ESTADO&quot; = (CASE WHEN (SELECT COUNT(A2.&quot;ItemCode&quot;)
        ///											FROM ORDR A
        ///											INNER JOIN RDR1 A1 ON A.&quot;DocEntry&quot; = A1.&quot;DocEntry&quot;
        ///											INNER JOIN OITM A2 ON A1.&quot;ItemCode&quot; = A2.&quot;ItemCode&quot;
        ///									 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SBO_EXX_INDO_PTN_OBJ017_ORDR {
            get {
                return ResourceManager.GetString("SBO_EXX_INDO_PTN_OBJ017_ORDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SBO_EXX_INDO_PTN_OBJ020_OPOR&quot;
        ///(
        ///	IN docEntry integer
        ///	, IN transaction_type nchar(1)
        ///	, OUT error integer
        ///	, OUT error_message nvarchar(200)
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///
        ///BEGIN 
        ///
        ///	IF :transaction_type = &apos;A&apos; OR :transaction_type = &apos;U&apos;  THEN		
        ///		UPDATE OPOR SET &quot;U_EXX_INDO_ESTADO&quot; =  (CASE WHEN &quot;CardCode&quot; in (Select &quot;U_EXX_INDO_PROV&quot; FROM &quot;@EXX_INDO_BASE&quot;) THEN &apos;PE&apos; ELSE &apos;NA&apos; END)
        ///		WHERE &quot;DocEntry&quot; = :docEntry;
        ///	END IF;
        ///END;.
        /// </summary>
        internal static string SBO_EXX_INDO_PTN_OBJ020_OPOR {
            get {
                return ResourceManager.GetString("SBO_EXX_INDO_PTN_OBJ020_OPOR", resourceCulture);
            }
        }
    }
}
